/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('locations').del()
  await knex('locations').insert([
    {name: 'Alabama', isConus: true},
    {name: 'Arizona', isConus: true},
    {name: 'Arkansas', isConus: true},
    {name: 'California', isConus: true},
    {name: 'Colorado', isConus: true},
    {name: 'Connecticut', isConus: true},
    {name: 'Delaware', isConus: true},
    {name: 'District of Columbia', isConus: true},
    {name: 'Georgia', isConus: true},
    {name: 'Idaho', isConus: true},
    {name: 'Illinois', isConus: true},
    {name: 'Indiana', isConus: true},
    {name: 'Iowa', isConus: true},
    {name: 'Kansas', isConus: true},
    {name: 'Kentucky', isConus: true},
    {name: 'Louisiana', isConus: true},
    {name: 'Maine', isConus: true},
    {name: 'Maryland', isConus: true},
    {name: 'Massachusetts', isConus: true},
    {name: 'Michigan', isConus: true},
    {name: 'Minnesota', isConus: true},
    {name: 'Missouri', isConus: true},
    {name: 'Montana', isConus: true},
    {name: 'Nebraska', isConus: true},
    {name: 'Nevada', isConus: true},
    {name: 'New Hampshire', isConus: true},
    {name: 'New Jersey', isConus: true},
    {name: 'New Mexico', isConus: true},
    {name: 'New York', isConus: true},
    {name: 'North Carolina', isConus: true},
    {name: 'North Dakota', isConus: true},
    {name: 'Ohio', isConus: true},
    {name: 'Oklahoma', isConus: true},
    {name: 'Oregon', isConus: true},
    {name: 'Penssylvania', isConus: true},
    {name: 'Rhode Island', isConus: true},
    {name: 'South Carolina', isConus: true},
    {name: 'South Dakota', isConus: true},
    {name: 'Tennessee', isConus: true},
    {name: 'Texas', isConus: true},
    {name: 'Utah', isConus: true},
    {name: 'Vermont', isConus: true},
    {name: 'Virgina', isConus: true},
    {name: 'Washington', isConus: true},
    {name: 'Wisconsin', isConus: true},
    {name: 'Wyoming', isConus: true},
    {name: 'Alaska', isConus: false},
    {name: 'Armed Forces Europe, Middle East, Africa', isConus: false},
    {name: 'Armed Forces Pacific', isConus: false},
    {name: 'Australia', isConus: false},
    {name: 'Bahrain', isConus: false},
    {name: 'Bahrain', isConus: false},
    {name: 'British Indian Ocean Territory', isConus: false},
    {name: 'Cuba', isConus: false},
    {name: 'Germany', isConus: false},
    {name: 'Greece', isConus: false},
    {name: 'Guam', isConus: false},
    {name: 'Hawaii', isConus: false},
    {name: 'Hungary', isConus: false},
    {name: 'Italy', isConus: false},
    {name: 'Japan', isConus: false},
    {name: 'Netherlands', isConus: false},
    {name: 'Norway', isConus: false},
    {name: 'Portugal', isConus: false},
    {name: 'Puerto Rico', isConus: false},
    {name: 'Singapore', isConus: false},
    {name: 'South Korea', isConus: false},
    {name: 'Spain', isConus: false},
    {name: 'Turkey', isConus: false},
    {name: 'United Kingdom', isConus: false},
    {name: 'U.S. Virgin Islands', isConus: false},
  ]);
};
